### ISSUE TITLE
[SBN] Final vqa

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-wtfengine#11]
Link: http://sbnation.sb12.sbndev.net/2015/5/21/8003383/sbn-randomizer-test
- [x] Sentinel not loading (falling back to georgia)
- [x] Gotham not loading — "this is a headline" small text and social buttons should be using gotham regular, "generate another" button should use gotham bold.

**Comment by kelseyscherer** [comment]
I upgraded, republished, saved -> Still seeing georgia instead of sentinel :cry: 

http://sbnation.sb12.sbndev.net/2015/5/21/8003383/sbn-randomizer-test

**Comment by aithnefeay** [comment]
You're on sandbox, which isn't licensed for Sentinel. If you embed on SBNation, it'll display.

**Comment by kelseyscherer** [comment]
GREAT!
