### ISSUE TITLE
Headline field not accepting multiple lines of input

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune-wtfengine#22]
Steps to reproduce:
1. Create a new randomizer
2. Input multiple headline templates, separating each one onto its own line.

Expected result:
You'd be able to hit enter, per the instructions, to separate each template per line.

Actual result:
Hitting enter in the field doesn't allow you to line-separate.

**Comment by caseymm** [comment]
Oh... It's related to this issue: https://github.com/voxmedia/autotune/issues/219. The typical default behavior for hitting enter on a form was to save the entire form before, which we didn't want. However, that disabled all `enter/return` related default behavior on forms, ergo this problem. Will look into it.
