### ISSUE TITLE
eater not calling fonts

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-wtfengine#29]
Currently:
![image](https://cloud.githubusercontent.com/assets/5759653/13114591/1947d686-d562-11e5-8af7-6d3574d4f347.png)

`Headers` Should be Whitney
Headline should be Whitney, but larger

Button type should be Glober Regular

Original spec:
![image](https://cloud.githubusercontent.com/assets/5759653/13114610/2e22c944-d562-11e5-8f00-d835c4d2683f.png)

**Comment by kelseyscherer** [comment]
Still seeing broken eater fonts:
![image](https://cloud.githubusercontent.com/assets/5759653/13159500/28bb2754-d660-11e5-829d-66d846036c1c.png)

**Comment by caseymm** [comment]
needs this link: https://cloud.typography.com/706184/6333152/css/fonts.css
