### ISSUE TITLE
recode: button should be using klavika bold, like all other buttons

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-wtfengine#32]
![image](https://cloud.githubusercontent.com/assets/5759653/14676924/7e07de48-06dd-11e6-9e21-193a7e7c616f.png)

vs

![image](https://cloud.githubusercontent.com/assets/5759653/14676947/88b2fe90-06dd-11e6-82d9-8135977d62da.png)

**Comment by caseymm** [comment]
I totally saw that and guessed that this would come up, haha. But I couldn't remember if the Randomizer had special styles or not, which is why I didn't change it when I first noticed.

**Comment by caseymm** [comment]
Should be fixed here: https://autotune.voxmedia.com/projects/recode-copy-of-ask-the-magic-mirror-a-yes-or-no-question#preview
