### ISSUE TITLE
[themes] `button_font_color` variable is not getting properly used (or set in some places)

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-wtfengine#34]
In the variables list, I see an option for setting button font color:
![image](https://cloud.githubusercontent.com/assets/5759653/15292444/21b33df8-1b51-11e6-8061-794a3cae3a60.png)

However, it's not being reflected in randomizer:
![image](https://cloud.githubusercontent.com/assets/5759653/15292457/2db5cee0-1b51-11e6-8dd3-233515dc1d43.png)

I'm also noticing it set incorrectly on a few themes, so once this is hooked up I will likely need to re-do vqa.

**Comment by kavyasukumar** [comment]
Wired up button font colors: https://github.com/voxmedia/autotune-wtfengine/commit/5688ad85e45a895a018ee5c12e982f05abeb7661. @kelseyscherer Please verify

**Comment by kelseyscherer** [comment]
:+1: Thanks @kavyasukumar
