### ISSUE TITLE
[themes] what is `REC Playground`?

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-wtfengine#35]
It's inheriting SB Nation colors?

**Comment by kavyasukumar** [comment]
@kelseyscherer All the themes listed are Chorus groups that autotune users have access to. VRGE and REC playground are sbnation blogs and they inherit sbnation theme. See https://github.com/voxmedia/vox-autotune/blob/master/config/theme_map.yml#L174-L1698 for full list of blogs currently wired to inherit sbnation themes

**Comment by kelseyscherer** [comment]
@kavyasukumar ok. I think there may be a few SBN blogs that were made for testing purposes (those seem like test blogs from their name?) so not sure the best way to handle. I guess we can keep them in instead of doing an individual audit of all the blog names.

**Comment by kavyasukumar** [comment]
@kelseyscherer Agreed. There is no way to tell if a blog is a test blog short of creating a list of 'not allowed' values.
