### ISSUE TITLE
[themes] `Vox Media` theme is inheriting polygon theme instead of Vox Media theme colors

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-wtfengine#36]
Also, I don't see Vox Media in autotune.voxmedia.com/themes, is that intentional?

**Comment by kavyasukumar** [comment]
@kelseyscherer It is here: https://autotune.voxmedia.com/themes/voxmedia

it is not set to inherit anything

**Comment by kelseyscherer** [comment]
@kavyasukumar Is there a reason I can't see it in the themes list? Also there was a trello card outlining the Vox Media theme, is there a reason we're not using that design? I thought we were going to go with a `Vox Media` theme, and call it Vox Media Default or something to that effect, and then there would be a separate "Open Source" theme. Realizing now there is a `generic` and `voxmedia` theme and I'm confused.

Trello card: https://trello.com/c/rqDdSc6X/548-dev-implement-generic-autotune-theme-due-4-21

Outstanding qs/ specs:

Question: In the open source version, what are we doing about Nitti?

Specs: Open Source: Let's go super simple, Georgia Bold for headers, Georgia regular for body. Color: #444444 (Can use same color for primary and secondary)

Vox Media / Default for everyone who isn't assigned a brand yet: Alright Sans Ultra for headers, Alright Sans Regular for body. Color: #3d3a44 (Can use same color for primary and secondary)

**Comment by kelseyscherer** [comment]
Talked through this in Slack. Going to address this separately, as a part of updating the themes UI. Will be moving generic and vox media themes into 1 default vox media theme. see trello for more info:
https://trello.com/c/1mfJkwZ6/649-dev-theme-ui-update
