### ISSUE TITLE
IE/FF/Chrome: Social share icons in headline generator's public url are not displaying properly

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune-wtfengine#6]
The headline generator has social share buttons, but for the majority of browsers the icons are not displaying properly.  Affected browsers:
IE 9-11: share icons are missing
FF/Chrome on Mac: empty boxes instead of icons are displayed
FFWin - characters inside of boxes displayed
ChromeWin - empty boxes instead of icons are displayed
Note: Safari on Mac displays icons properly

1) Open public url for a headline generator in one of the following browsers
Example - https://apps.voxmedia.com/at/name-my-pet/

Chrome Mac Headline
![chrome mac headline](https://cloud.githubusercontent.com/assets/11615553/7712228/0edb8c52-fe3e-11e4-8651-965de0349bcb.png)

FF Mac Headline
![ff mac headline](https://cloud.githubusercontent.com/assets/11615553/7712273/62168c0a-fe3e-11e4-8890-e0add251e4f6.png)

**Comment by kelseyscherer** [comment]
Noticed this during vqa, too, for all verticals. Going to assign to @alfeay who is working on some visual stuff. (But can reassign anyone to this if they want to hop on)
