### ISSUE TITLE
Facebook social share link for headline generator's public url is broken

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune-wtfengine#7]
A reader may use the Facebook share button in the headline generator 

1) Open a published headline generator
https://apps.voxmedia.com/at/name-my-pet/
2) Click the Facebook share button
https://www.facebook.com/dialog/feed?display=popup&app_id=&link=https%3A%2F%2Fapps.voxmedia.com%2Fat%2Fname-my-pet%2F&name=what%20should%20I%20name%20my%20pet%3F%20(do%20not%20delete)&description=You%20should%20name%20your%20pet%20mr%20snuggles

Expected: Facebook pop-up window with social shared link
Actual: Error message
![headline fb share](https://cloud.githubusercontent.com/assets/11615553/7712637/5fc8cc9a-fe40-11e4-9bca-75dad46813e6.gif)

**Comment by aithnefeay** [comment]
MVP fix implemented, but it would be nice to contact social and actually get an app id from a Vox Media Facebook account.
