### ISSUE TITLE
Certain vertical-specific fonts not displaying on production

### ISSUE THREAD

**Issue by aithnefeay** [voxmedia/autotune-wtfengine#8]
- [ ] Racked - Franklin ITC Cond
- [ ] SBNation - Sentinel
- [ ] ...more coming

**Comment by aithnefeay** [comment]
On second thought, we probably just need to vqa this. cc: @kelseyscherer

**Comment by kelseyscherer** [comment]
@alfeay Gonna close this and open vertical specific vqa tickets.
