### ISSUE TITLE
Should twitter share URL point directly to the embed? 

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune-wtfengine#9]
e.g. 

```
You should name your pet prince snuggles https://apps.voxmedia.com/at-preview/name-my-pet/?initialWidth=490&childId=name-my-pet__graphic via @
```

**Comment by aithnefeay** [comment]
**Solutions**
1. Include a field for the post url in which the project will be embedded, which is then used as the share url.
2. Share links will direct to the project itself, bypassing the vertical entirely. Basically a dead end.

I think Solution 1 is our best bet. If there are no objections, I'll implement.

**Comment by ryanmark** [comment]
http://www.nczonline.net/blog/2013/04/16/getting-the-url-of-an-iframes-parent/
